name: Netology CICD

on:
    push:
        branches: [main]

jobs:
    testing:
        runs-on: ubuntu-latest
        env:
            PG_NAME: ${{ secrets.PG_NAME }}
            PG_USER: ${{ secrets.PG_USER }}
            PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
            PG_HOST: ${{ secrets.PG_HOST }}
            PG_PORT: ${{ secrets.PG_PORT }}
        services:
            postgres_main:
                image: postgres:latest
                env:
                    POSTGRES_USER: ${{ env.PG_USER }}
                    POSTGRES_PASSWORD: ${{ env.PG_PASSWORD }}
                    POSTGRES_DB: ${{ env.PG_NAME }}
                ports:
                    - 5432:5432
                options:
                    --health-cmd pg_isready
                    --health-interval 5s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - name: Проверяем репозиторий на наличие изменений
              uses: actions/checkout@v2

            - name: Устанавливаем Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.12

            - name: Устанавливаем зависимости
              run: pip install -r requirements.txt

            - name: Литинг кода
              run: flake8 logistic stocks_products --exclude migrations --ignore E501,F401
    deploy:
        name: Доставка кода
        needs: testing
        runs-on: ubuntu-latest
        steps:
            - name: Запуск скрипта обновления
              uses: appleboy/ssh-action@master
              env:
                  PG_NAME: ${{ secrets.PG_NAME }}
                  PG_USER: ${{ secrets.PG_USER }}
                  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
                  PG_HOST: ${{ secrets.PG_HOST }}
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      cd /var/www/netology2
                      git pull
                      source .venv/bin/activate
                      pip install -r requirements.txt
                      python3 manage.py migrate
                      echo "${{ secrets.SSH_PASSWORD }}" | sudo -S ./.restart_service.sh
